@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Apr 28 21:33:57 -0700 2020
REM SW Build 2729669 on Thu Dec  5 04:49:17 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto bfc4ab3f0e5d4e8b96bf06711011f336 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L xlslice_v1_0_2 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot cfg_tb_design_1_wrapper_behav xil_defaultlib.cfg_tb_design_1_wrapper xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto bfc4ab3f0e5d4e8b96bf06711011f336 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L xlslice_v1_0_2 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot cfg_tb_design_1_wrapper_behav xil_defaultlib.cfg_tb_design_1_wrapper xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
