@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Feb 20 10:42:12 -0800 2020
REM SW Build 2729669 on Thu Dec  5 04:49:17 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 09f80b588b22475eb171a4441a85b04f --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_logic_circuit_F2_behav xil_defaultlib.tb_logic_circuit_F2 -log elaborate.log"
call xelab  -wto 09f80b588b22475eb171a4441a85b04f --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_logic_circuit_F2_behav xil_defaultlib.tb_logic_circuit_F2 -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
