# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/adder_subtractor/adder_subtractor.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor || ORIG_REF_NAME==adder_subtractor} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_FA_0_0/adder_subtractor_FA_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_FA_0_0 || ORIG_REF_NAME==adder_subtractor_FA_0_0} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_FA_0_1/adder_subtractor_FA_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_FA_0_1 || ORIG_REF_NAME==adder_subtractor_FA_0_1} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_FA_0_2/adder_subtractor_FA_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_FA_0_2 || ORIG_REF_NAME==adder_subtractor_FA_0_2} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_FA_0_3/adder_subtractor_FA_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_FA_0_3 || ORIG_REF_NAME==adder_subtractor_FA_0_3} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_xlslice_0_0/adder_subtractor_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_xlslice_0_0 || ORIG_REF_NAME==adder_subtractor_xlslice_0_0} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_xlslice_0_1/adder_subtractor_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_xlslice_0_1 || ORIG_REF_NAME==adder_subtractor_xlslice_0_1} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_xlslice_1_0/adder_subtractor_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_xlslice_1_0 || ORIG_REF_NAME==adder_subtractor_xlslice_1_0} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_xlslice_1_1/adder_subtractor_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_xlslice_1_1 || ORIG_REF_NAME==adder_subtractor_xlslice_1_1} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_xlslice_1_2/adder_subtractor_xlslice_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_xlslice_1_2 || ORIG_REF_NAME==adder_subtractor_xlslice_1_2} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_xlslice_1_3/adder_subtractor_xlslice_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_xlslice_1_3 || ORIG_REF_NAME==adder_subtractor_xlslice_1_3} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_xlslice_1_4/adder_subtractor_xlslice_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_xlslice_1_4 || ORIG_REF_NAME==adder_subtractor_xlslice_1_4} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_xlslice_1_5/adder_subtractor_xlslice_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_xlslice_1_5 || ORIG_REF_NAME==adder_subtractor_xlslice_1_5} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_util_vector_logic_0_0/adder_subtractor_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_util_vector_logic_0_0 || ORIG_REF_NAME==adder_subtractor_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_util_vector_logic_0_1/adder_subtractor_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_util_vector_logic_0_1 || ORIG_REF_NAME==adder_subtractor_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_util_vector_logic_0_2/adder_subtractor_util_vector_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_util_vector_logic_0_2 || ORIG_REF_NAME==adder_subtractor_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_util_vector_logic_0_3/adder_subtractor_util_vector_logic_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_util_vector_logic_0_3 || ORIG_REF_NAME==adder_subtractor_util_vector_logic_0_3} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_xlconstant_0_0/adder_subtractor_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_xlconstant_0_0 || ORIG_REF_NAME==adder_subtractor_xlconstant_0_0} -quiet] -quiet

# IP: bd/adder_subtractor/ip/adder_subtractor_xlconcat_0_0/adder_subtractor_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_xlconcat_0_0 || ORIG_REF_NAME==adder_subtractor_xlconcat_0_0} -quiet] -quiet

# XDC: bd/adder_subtractor/adder_subtractor_ooc.xdc
