# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/adder_2bit/adder_2bit.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_2bit || ORIG_REF_NAME==adder_2bit} -quiet] -quiet

# IP: bd/adder_2bit/ip/adder_2bit_FA_0_0/adder_2bit_FA_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_2bit_FA_0_0 || ORIG_REF_NAME==adder_2bit_FA_0_0} -quiet] -quiet

# IP: bd/adder_2bit/ip/adder_2bit_FA_0_1/adder_2bit_FA_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_2bit_FA_0_1 || ORIG_REF_NAME==adder_2bit_FA_0_1} -quiet] -quiet

# IP: bd/adder_2bit/ip/adder_2bit_xlslice_0_0/adder_2bit_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_2bit_xlslice_0_0 || ORIG_REF_NAME==adder_2bit_xlslice_0_0} -quiet] -quiet

# IP: bd/adder_2bit/ip/adder_2bit_xlslice_0_1/adder_2bit_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_2bit_xlslice_0_1 || ORIG_REF_NAME==adder_2bit_xlslice_0_1} -quiet] -quiet

# IP: bd/adder_2bit/ip/adder_2bit_xlslice_0_2/adder_2bit_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_2bit_xlslice_0_2 || ORIG_REF_NAME==adder_2bit_xlslice_0_2} -quiet] -quiet

# IP: bd/adder_2bit/ip/adder_2bit_xlslice_2_0/adder_2bit_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_2bit_xlslice_2_0 || ORIG_REF_NAME==adder_2bit_xlslice_2_0} -quiet] -quiet

# IP: bd/adder_2bit/ip/adder_2bit_xlconstant_0_0/adder_2bit_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_2bit_xlconstant_0_0 || ORIG_REF_NAME==adder_2bit_xlconstant_0_0} -quiet] -quiet

# IP: bd/adder_2bit/ip/adder_2bit_xlconcat_0_0/adder_2bit_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_2bit_xlconcat_0_0 || ORIG_REF_NAME==adder_2bit_xlconcat_0_0} -quiet] -quiet

# IP: bd/adder_2bit/ip/adder_2bit_FA_1_0/adder_2bit_FA_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_2bit_FA_1_0 || ORIG_REF_NAME==adder_2bit_FA_1_0} -quiet] -quiet

# IP: bd/adder_2bit/ip/adder_2bit_FA_1_1/adder_2bit_FA_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_2bit_FA_1_1 || ORIG_REF_NAME==adder_2bit_FA_1_1} -quiet] -quiet

# IP: bd/adder_2bit/ip/adder_2bit_xlslice_3_0/adder_2bit_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_2bit_xlslice_3_0 || ORIG_REF_NAME==adder_2bit_xlslice_3_0} -quiet] -quiet

# IP: bd/adder_2bit/ip/adder_2bit_xlslice_3_1/adder_2bit_xlslice_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_2bit_xlslice_3_1 || ORIG_REF_NAME==adder_2bit_xlslice_3_1} -quiet] -quiet

# IP: bd/adder_2bit/ip/adder_2bit_xlslice_3_2/adder_2bit_xlslice_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_2bit_xlslice_3_2 || ORIG_REF_NAME==adder_2bit_xlslice_3_2} -quiet] -quiet

# IP: bd/adder_2bit/ip/adder_2bit_xlslice_3_3/adder_2bit_xlslice_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_2bit_xlslice_3_3 || ORIG_REF_NAME==adder_2bit_xlslice_3_3} -quiet] -quiet

# XDC: bd/adder_2bit/adder_2bit_ooc.xdc
