# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/adder_subtractor_4bit/adder_subtractor_4bit.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_4bit || ORIG_REF_NAME==adder_subtractor_4bit} -quiet] -quiet

# IP: bd/adder_subtractor_4bit/ip/adder_subtractor_4bit_FA_0_0/adder_subtractor_4bit_FA_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_4bit_FA_0_0 || ORIG_REF_NAME==adder_subtractor_4bit_FA_0_0} -quiet] -quiet

# IP: bd/adder_subtractor_4bit/ip/adder_subtractor_4bit_FA_0_1/adder_subtractor_4bit_FA_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_4bit_FA_0_1 || ORIG_REF_NAME==adder_subtractor_4bit_FA_0_1} -quiet] -quiet

# IP: bd/adder_subtractor_4bit/ip/adder_subtractor_4bit_FA_0_2/adder_subtractor_4bit_FA_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_4bit_FA_0_2 || ORIG_REF_NAME==adder_subtractor_4bit_FA_0_2} -quiet] -quiet

# IP: bd/adder_subtractor_4bit/ip/adder_subtractor_4bit_FA_0_3/adder_subtractor_4bit_FA_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_4bit_FA_0_3 || ORIG_REF_NAME==adder_subtractor_4bit_FA_0_3} -quiet] -quiet

# IP: bd/adder_subtractor_4bit/ip/adder_subtractor_4bit_xlslice_0_0/adder_subtractor_4bit_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_4bit_xlslice_0_0 || ORIG_REF_NAME==adder_subtractor_4bit_xlslice_0_0} -quiet] -quiet

# IP: bd/adder_subtractor_4bit/ip/adder_subtractor_4bit_xlslice_0_1/adder_subtractor_4bit_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_4bit_xlslice_0_1 || ORIG_REF_NAME==adder_subtractor_4bit_xlslice_0_1} -quiet] -quiet

# IP: bd/adder_subtractor_4bit/ip/adder_subtractor_4bit_xlslice_0_2/adder_subtractor_4bit_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_4bit_xlslice_0_2 || ORIG_REF_NAME==adder_subtractor_4bit_xlslice_0_2} -quiet] -quiet

# IP: bd/adder_subtractor_4bit/ip/adder_subtractor_4bit_xlslice_0_3/adder_subtractor_4bit_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_4bit_xlslice_0_3 || ORIG_REF_NAME==adder_subtractor_4bit_xlslice_0_3} -quiet] -quiet

# IP: bd/adder_subtractor_4bit/ip/adder_subtractor_4bit_xlslice_0_4/adder_subtractor_4bit_xlslice_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_4bit_xlslice_0_4 || ORIG_REF_NAME==adder_subtractor_4bit_xlslice_0_4} -quiet] -quiet

# IP: bd/adder_subtractor_4bit/ip/adder_subtractor_4bit_xlslice_0_5/adder_subtractor_4bit_xlslice_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_4bit_xlslice_0_5 || ORIG_REF_NAME==adder_subtractor_4bit_xlslice_0_5} -quiet] -quiet

# IP: bd/adder_subtractor_4bit/ip/adder_subtractor_4bit_xlslice_0_6/adder_subtractor_4bit_xlslice_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_4bit_xlslice_0_6 || ORIG_REF_NAME==adder_subtractor_4bit_xlslice_0_6} -quiet] -quiet

# IP: bd/adder_subtractor_4bit/ip/adder_subtractor_4bit_xlslice_0_7/adder_subtractor_4bit_xlslice_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_4bit_xlslice_0_7 || ORIG_REF_NAME==adder_subtractor_4bit_xlslice_0_7} -quiet] -quiet

# IP: bd/adder_subtractor_4bit/ip/adder_subtractor_4bit_xlconstant_0_1/adder_subtractor_4bit_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_4bit_xlconstant_0_1 || ORIG_REF_NAME==adder_subtractor_4bit_xlconstant_0_1} -quiet] -quiet

# IP: bd/adder_subtractor_4bit/ip/adder_subtractor_4bit_xlconcat_0_0/adder_subtractor_4bit_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_subtractor_4bit_xlconcat_0_0 || ORIG_REF_NAME==adder_subtractor_4bit_xlconcat_0_0} -quiet] -quiet

# XDC: bd/adder_subtractor_4bit/adder_subtractor_4bit_ooc.xdc
